spring.application.name=jwt

spring.datasource.url=jdbc:postgresql://localhost/jwt
spring.datasource.username=postgres
spring.datasource.password=b@se312

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

jwt.secret=a42c648d3de8bcd506c00780e44e93bfacd98247b16081d4790411174021f745eb9bc51de5ca0f0b2983c3261e19819992c24df9c97cc919bb29c8a109daad77